starting-balance: 0
currency-symbol: '✦'
default-currency: shards
max-money: 10000000000000
min-money: 0
economy-log-enabled: false
auto-save-interval-seconds: 300
online-shard-reward:
  enabled: true
  amount: 1
  interval-seconds: 60

currencies:
  Shards:
    symbol: '✦'
    command-alias: shards
    starting-balance: 0
    max-money: 10000000000000
    min-money: 0
