name: BestEconomy
main: com.controlbro.besteconomy.BestEconomyPlugin
version: 1.0.0
api-version: 1.26
author: Controlbro
softdepend: [Vault]

commands:
  eco:
    description: Economy command for Shards.
    aliases: [economy]
    usage: /eco
  balance:
    description: Check balance.
    aliases: [bal]
    usage: /balance [player]
  baltop:
    description: View top balances.
    usage: /baltop [page]
  pay:
    description: Pay another player.
    usage: /pay <player> <amount>
  besteconomy:
    description: BestEconomy admin command.
    usage: /besteconomy reload

permissions:
  besteconomy.eco.give:
    description: Allows giving Shards.
    default: op
  besteconomy.eco.take:
    description: Allows taking Shards.
    default: op
  besteconomy.eco.reset:
    description: Allows resetting Shards.
    default: op
  besteconomy.balance:
    description: Allows checking own balance.
    default: true
  besteconomy.balance.others:
    description: Allows checking others' balances.
    default: op
  besteconomy.baltop:
    description: Allows viewing baltop.
    default: true
  besteconomy.pay:
    description: Allows paying other players.
    default: true
  besteconomy.reload:
    description: Allows reloading the plugin.
    default: op
